### ISSUE TITLE
ctdb 4.9.X breaks ceph-smb role

### ISSUE THREAD

**Issue by rmacqueen12** [45Drives/ceph-ansible-45d#12]
**Bug Report**

What happened:

What you expected to happen:

How to reproduce it (minimal and precise):

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
* ceph-ansible version (e.g. `git head or tag or stable branch`):
* Ceph version (e.g. `ceph -v`):

**Comment by bkelly16** [comment]
Fixed in v1.1.. for pre 4.9 CTDB support use v1.0
