### ISSUE TITLE
ceph-facts fails on set_grafana_addr when using ipv6

### ISSUE THREAD

**Issue by rmacqueen12** [45Drives/ceph-ansible-45d#7]
Problem lies here:
roles/ceph-facts/tasks/facts.yml
 
Need to add conditional to check if ipv4 or ipv6 and set "'ansible_all_ipv4_addresses" accordingly

- name: set grafana_server_addr fact
  set_fact:
    grafana_server_addr: "{{ (hostvars[groups[grafana_server_group_name][0] | default(groups[mgr_group_name][0])])['ansible_all_ipv4_addresses'] | ipaddr(public_network) | first }}"
  when:  groups.get(grafana_server_group_name, []) | length > 0 or groups.get(mgr_group_name, []) | length > 0

**Comment by bkelly16** [comment]
closed in 1.3
