### ISSUE TITLE
ceph-smb  fails when using msgr2

### ISSUE THREAD

**Issue by rmacqueen12** [45Drives/ceph-ansible-45d#9]
In roles/ceph-samba/tasks/config_cephfs.yml

    - name: config_cephfs | Mount cephfs as admin user 

port is hard-coded to 6789, needs to be 3300 when using msgr2

Leaving it out should default to the correct port....

**Comment by bkelly16** [comment]
fixed in master and 1.1.
Solution was to remove port altogether in the fstab entry.
